# Add these automations to get notifications

# Stock Available Alert
- id: apple_stock_alert
  alias: "iPhone Stock Available"
  trigger:
    - platform: state
      entity_id: binary_sensor.apple_store_stock_available
      to: "on"
  action:
    - service: notify.mobile_app_your_phone
      data:
        title: "🍎 iPhone Available!"
        message: >
          {{ state_attr('sensor.apple_store_stock_available', 'available_items') | length }} 
          items available at Apple Stores
        data:
          priority: high
          ttl: 0

# Daily Status Report
- id: apple_stock_daily_report
  alias: "Daily Apple Stock Report"
  trigger:
    - platform: time
      at: "09:00:00"
  action:
    - service: notify.mobile_app_your_phone
      data:
        title: "📊 Daily Apple Stock Report"
        message: >
          Last check: {{ states('sensor.apple_store_last_check') }}
          Monitoring {{ state_attr('sensor.apple_store_stock_available', 'stores_checked') }} stores
          for {{ state_attr('sensor.apple_store_stock_available', 'products_checked') }} products

# Script Health Check
- id: apple_monitor_health
  alias: "Apple Monitor Health Check"
  trigger:
    - platform: time_pattern
      hours: "/2"  # Every 2 hours
  condition:
    - condition: template
      value_template: >
        {{ (now() - states.sensor.apple_store_last_check.last_changed).total_seconds() > 3600 }}
  action:
    - service: notify.mobile_app_your_phone
      data:
        title: "⚠️ Apple Monitor Issue"
        message: "Apple Store monitor hasn't updated in over 1 hour"